### ISSUE TITLE
Request to add solution for the GFG problem "Prefix To Infix" 

### ISSUE THREAD

**Issue by twnkl2713** [aman247av/Hacktoberfest-Coding-Challenges#31]
I would like to request the addition of a solution for the GFG problem "Prefix to Infix Conversion". This feature would allow users to convert prefix expressions to infix notation, enhancing usability in mathematical computations.
Please assign me this task @aman247av

**Comment by aman247av** [comment]
Yes sure go ahead!!

**Comment by twnkl2713** [comment]
can u pls add the label hacktoberfest to it?

**Comment by aman247av** [comment]
@twinkle485 any update on this issue... or shall i close this
