### ISSUE TITLE
To add "Best time to buy and sell stock-II" leetcode problem

### ISSUE THREAD

**Issue by Amit-yadav099** [aman247av/Hacktoberfest-Coding-Challenges#41]
hello @aman247av 
i want to add leetcode -122 "best time to buy and sell stock -II" problem
i m a newbie in github, kindly assign this task to me under hacktoberdest2024

problem statment: You are given an integer array prices where prices[i] is the price of a given stock on the ith day.
On each day, you may decide to buy and/or sell the stock. You can only hold at most one share of the stock at any time. However, you can buy it then immediately sell it on the same day.

Find and return the maximum profit you can achieve.

Input: prices = [7,1,5,3,6,4]
Output: 7
Explanation: Buy on day 2 (price = 1) and sell on day 3 (price = 5), profit = 5-1 = 4.
Then buy on day 4 (price = 3) and sell on day 5 (price = 6), profit = 6-3 = 3.
Total profit is 4 + 3 = 7.

**Comment by mdsahilnoob** [comment]
Hey @aman247av, I would like to work on this issue, Can you assign me?
