### ISSUE TITLE
Roman to Interger 

### ISSUE THREAD

**Issue by S-125** [aman247av/Hacktoberfest-Coding-Challenges#5]
Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.

Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000
For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

**Comment by S-125** [comment]
I want to add java program on converting Roman to Integer .. please assign me this problem under hacktoberfest 2024

**Comment by aman247av** [comment]
Go ahead... refer to naming convention and format while making PULL Request

**Comment by S-125** [comment]
@aman247av I have made a pull request please review it .

**Comment by aman247av** [comment]
Great!!.. Approach looks good to me.
